name: Release
on:
  push:
    tags:
      - "*"
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 15]
      fail-fast: false
    steps:
      - name: "Checkout repo"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - name: "Setup Java ${{ matrix.java }}"
        uses: "actions/setup-java@v1"
        with:
          java-version: ${{ matrix.java }}
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Cache Gradle wrapper"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/notifications
          key: "gradle-wrapper-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}"
      - name: "Cache Gradle dependencies"
        uses: "actions/cache@v2"
        with:
          path: "~/.gradle/caches"
          key: "gradle-caches-${{ runner.os }}-${{ hashFiles('build.gradle') }}"
      - name: "Gradle check"
        run: "./gradlew check --continue"
  publish:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: "Checkout repo"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - name: "Setup Java"
        uses: "actions/setup-java@v1"
        with:
          java-version: 8
      - name: "Cache Gradle wrapper"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/notifications
          key: "gradle-wrapper-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}"
      - name: "Cache Gradle dependencies"
        uses: "actions/cache@v2"
        with:
          path: "~/.gradle/caches"
          key: "gradle-caches-${{ runner.os }}-${{ hashFiles('build.gradle') }}"
      - name: "Gradle publish"
        env:
          CLOJARS_USER: ${{ secrets.CLOJARS_USER }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
        run: "./gradlew publish"
